Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/compilation/module_compiler.py", line 405, in compile
    function.evaluate("Compiling", inputset, configuration, function_artifacts)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/compilation/module_compiler.py", line 233, in evaluate
    self.trace(first_sample, artifacts)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/compilation/module_compiler.py", line 146, in trace
    self.graph = Tracer.trace(self.function, parameters, location=self.location)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/tracing/tracer.py", line 75, in trace
    node = Node.input(param, parameters[param])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/representation/node.py", line 149, in input
    return Node([value], value, Operation.Input, InputEvaluator(), {"name": name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/concrete/fhe/representation/node.py", line 190, in __init__
    self.tag = ".".join(tag_context.stack)
                        ^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'stack'
